language: python
python:
  - "2.7"
before_install: 
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get remove -y libgdal1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -y
  - sudo apt-get install -y gdal-bin
install: pip install -r requirements.txt
script:  python tests.py
branches:
  only:
    - master
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/6ee3ad02-a7ba-4f9d-aab5-fc4ce55a59d5/status
